---
# Este playbook se encarga de hacer el despliegue de los tres roles
# que componen el proceso de instalación y configuración de un 
# Stack LAMP.
# Todos los roles son compatibles con distribuciones derivadas de RedHat y Debian

# Primer role a implementar. Contiene paquetes esenciales para el correcto funcionamiento
# de los servidores a configurar.
- name: Aplicar configuraciones basicas en los servidores
  hosts: all
  remote_user: ansible
  become: yes

  roles:
    - common


# Segundo role. Instala configura Apache, con soporte para contenido PHP
- name: Desplegar Servidores Web
  hosts: all
  remote_user: ansible
  become: yes

  roles:
    - web


# Tercer role. Despliegue de servidor de bases de datos
- name: Desplegar servidores de bases de datos
  hosts: all
  remote_user: ansible
  become: yes

  roles:
    - db
