---
# Este rol contiene las tareas en comun que se ejecutaran en todos los nodos
# sin importar su distribucion (derivados de RedHat o Debian)


# Lineas 8, 9 y 10 son para testear de manera independiente el rol como playbook

# - hosts: all
#   become: yes
#   tasks:


  # Instalacion de Epel en caso de derivados de RedHat
    - name: Install Epel
      yum:
        name: epel-release
        state: present
      when: ansible_facts['os_family'] == "RedHat"

# Instalacion de chrony en caso de derivados de RedHat
    - name: Install chrony RedHat
      yum:
        name: chrony
        state: present
      when: ansible_facts['os_family'] == "RedHat"  

# Instalacion de chrony en caso de derivados de Debian
    - name: Install chrony Debian
      apt:
        name: chrony
        state: present
      when: ansible_facts['os_family'] == "Debian"

#Instalacion de paquetes de seguridad en derivados de RedHat
    - name: Install common dependencies
      yum: 
        name: "{{ packages }}"
        state: installed
      vars:
        packages: 
        - python3-libselinux
        - python3-libsemanage
        - policycoreutils-python-utils
        - firewalld
      when: ansible_facts['os_family'] == "RedHat" 

#Archivo de configuracion de Chrony
    - name: Configure chrony file
      template: src=../templates/chrony.conf.j2 dest=/etc/chrony.conf

#Iniciar servicio Chronyd
    - name: Start the chrony service
      service: name=chronyd state=started enabled=yes