---
# Este rol contiene las tareas en comun que se ejecutaran en todos los nodos
# sin importar su distribucion (derivados de RedHat o Debian)


# Lineas 8, 9 y 10 son para testear de manera independiente el rol como playbook

  # - hosts: all
  #   become: yes
  #   tasks:


 # Instalacion de Epel derivados de RedHat
    - name: RedHat - Instalar Epel
      yum:
        name: epel-release
        state: present
      when: ansible_facts['os_family'] == "RedHat"

# Instalacion de chrony en derivados de RedHat
    - name: RedHat - Instalar Chrony
      yum:
        name: chrony
        state: present
      when: ansible_facts['os_family'] == "RedHat"  

# Instalacion de chrony en derivados de Debian
    - name: Debian - Instalar Chrony 
      apt:
        name: chrony
        state: present
      when: ansible_facts['os_family'] == "Debian"

# Instalacion de paquetes de seguridad en derivados de RedHat
    - name: RedHat - Security Packages
      yum: 
        name: "{{ packages }}"
        state: installed
      vars:
        packages: 
        - python3-libselinux
        - python3-libsemanage
        - policycoreutils-python-utils
        - firewalld
      when: ansible_facts['os_family'] == "RedHat" 

# Archivo de configuracion de Chrony - Configuracion comun
# Como template se utiliza el archivo del directorio templates
    - name: Copiar archivo de configuracion Crony
      template: src=../templates/chrony.conf.j2 dest=/etc/chrony.conf

#Iniciar servicio Chronyd - Configuracion comun 
    - name: Iniciar servicio Chrony
      service: name=chronyd state=started enabled=yes