---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp
# Instalacion en caso de derivados de RedHat 
  yum: name=ntp state=present   
  when: ansible_facts['os_family'] == "RedHat"
# Instalacion en caso de derivados de Debian  
  apt: name=ntp state=present
  when: ansible_facts['os_family'] == "Debian"
  tags: ntp

# - name: Install common dependencies
#   yum: name={{ item }} state=installed
#   with_items:
#    - libselinux-python
#    - libsemanage-python
#    - firewalld

# - name: Configure ntp file
#   template: src=ntp.conf.j2 dest=/etc/ntp.conf
#   tags: ntp
#   notify: restart ntp

# - name: Start the ntp service
#   service: name=ntpd state=started enabled=yes
#   tags: ntp