---
# This playbook contains common plays that will be run on all nodes.
- hosts: all
  become: yes
  tasks:
  # Instalacion de Epel
    - name: Install Epel
      dnf:
        name: epel-release
        state: present
      when: ansible_facts['os_family'] == "RedHat"

# Instalacion de ntp en caso de derivados de RedHat
    - name: Install ntp RedHat
      dnf:
        name: chrony
        state: present
      when: ansible_facts['distribution'] == "CentOS"      
# Instalacion en caso de derivados de Debian
# - name: Install ntp Debian    
#   apt:
#     name: ntp
#     state: present
#   when: ansible_facts['os_family'] == "Debian"
#   tags: ntp

# - name: Install common dependencies
#   yum: name={{ item }} state=installed
#   with_items:
#    - libselinux-python
#    - libsemanage-python
#    - firewalld

# - name: Configure ntp file
#   template: src=ntp.conf.j2 dest=/etc/ntp.conf
#   tags: ntp
#   notify: restart ntp

# - name: Start the ntp service
#   service: name=ntpd state=started enabled=yes
#   tags: ntp