# Lineas 8, 9 y 10 son para testear de manera independiente el rol como playbook

- hosts: all
  become: yes
  tasks:

# Incluyo archivo de variables
  - name: Incluyo variables    
    include_vars:
      dir: ../../../group_vars/
      extensions:
      - 'yml'

#### Debian ####
  - name: Instalo MySQL y sus dependencies
    apt: 
      name: "{{ packages }}"
      state: present
    vars:
        packages:         
        - mysql-server      
        - python3-pip
    when: ansible_facts['os_family'] == "Debian"

#### RedHat ###
  - name: Instalo MySQL y sus dependencies
    yum: 
      name: "{{ packages }}"
      state: present
    vars:
        packages:
        - mysql-server
        - python3-pip        
    when: ansible_facts['os_family'] == "RedHat"
  
  - name: Instalo MySQL-python
    pip:
      name: mysql-connector
      state: present

#### RedHat ###
  - name: Configuro SELinux para dejar conectar con el motor mysql en cualquier puerto
    seboolean: name=mysql_connect_any state=true persistent=yes
    when: ansible_facts['os_family'] == "RedHat"

  - name: Creo el archivo de configuracion para Mysql
    template:
      src: ../templates/my.cnf.j2
      dest: /etc/my.cnf

  - name: Creo archivos de log de MySQL
    file:
      path: /var/log/mysqld.log
      state: touch
      owner: mysql
      group: mysql
      mode: '0775'

  - name: Creo el directorio para PID de MySQL
    file:
      path: /var/run/mysqld
      state: directory
      owner: mysql
      group: mysql
      mode: '0775'

  - name: Levanto MySQL
    service: name=mysql state=started enabled=yes

#### RedHat ###
  - name: Levanto firewalld
    service: name=firewalld state=started enabled=yes
    when: ansible_facts['os_family'] == "RedHat"

#### Debian ###
  - name: Levanto ufw
    service: name=ufw state=started enabled=yes
    when: ansible_facts['os_family'] == "Debian"

#### RedHat ###
  - name: inserto regla de firewalld
    firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes
    when: ansible_facts['os_family'] == "RedHat"

#### Debian ####
# Creo la regla de ufw para MySQL
  - name: inserto regla de ufw
    ufw:
      rule: allow
      port: "{{ mysql_port }}"
      proto: tcp
    when: ansible_facts['os_family'] == "Debian"



# #### RedHat ###
# - name: Create Application Database
#   mysql_db:
#    name: {{ dbname }}
#    state: present

# - name: Create Application DB User
#   mysql_user:
#    name: {{ dbuser }}
#    password: {{ upassword }}
#    priv: "*.*:ALL host='%'"
#    state: present